//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
		public class support
		{
				public support ()
				{
				}
		int getKeyNumber(KeyPositionEnum keyenum){
			string keystr = keyenum.ToString ();
			int keynumber = 0;
			switch (keystr.Substring(keystr.Length -1,1)) {
			case "C":
				keynumber = 14;
				break;
			case "D":
				keynumber = 15;
				break;
			case "E":
				keynumber = 16;
				break;
			case "F":
				keynumber = 17;
				break;
			case "G":
				keynumber = 18;
				break;
			case "A":
				keynumber = 19;
				break;
			case "H":
				keynumber = 20;
				break;
			default:
				keynumber = 0;
				break;
			}
			if(keystr.StartsWith("lowlow")){
				return keynumber - 14;
			}else if(keystr.StartsWith("low")){
				return keynumber - 7;
			}else if(keystr.StartsWith("highhigh")){
				return keynumber + 14;
			}else if(keystr.StartsWith("high")){
				return keynumber +7;
			}
			return keynumber;
			
		}
		}
}

